### ISSUE TITLE
Refactor Javascript code

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#1]
Javascript code should be refactored to improve ease of development and maintenance, use consistent patterns for common operations, and follow best practices.

@lilliputten Please do what you think is necessary, but let's try to avoid a complicated build process or big frameworks which make simple fixes from non-Javascript experts hard to do in the future. I trust your judgment.

**Comment by cmutel** [comment]
- Module management system (to discuss, to llok for options).
- Extract/redistribute all the embedded code.
- Dev tools for styles (linting, prettifying, etc).

@lilliputten All of this is OK, let's make sure it is documented and easy to do though.

**Comment by lilliputten** [comment]
Sub-task for styles liniting, PR #14:

https://github.com/cauldron/bw_matchbox/pull/14

**Comment by cmutel** [comment]
No conflicts after merging #13
