### ISSUE TITLE
In `index` view, users without the role `editors` should not see `Add` match button

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#100]
<img width="1218" alt="Screenshot 2023-08-10 at 19 54 16" src="https://github.com/cauldron/bw_matchbox/assets/645217/918316a8-4e1d-4a5e-9dc3-60e4c1d50717">

Currently users logged in as "reviewers" (or anything other than editors) in the `index` view can see a "Matched" column with links to "/match/<id>", which all lead to 403 errors.

Instead, they should see a "Match" column, which should show:

- If there is a proxy (i.e. `proxy_id` is truthy), a button linking to the proxy dataset, with the text "Proxy dataset". Use the JSON field "proxy_url", see 8c45e36085b0fdc1ae1fe7ffa984248ae8063b22.
- If there is a match type but no `proxy_id`, then display "No match needed"
- Else display "Unmatched"

You can get the user role with `{{ config.role }}` in the template, see [an example here](https://github.com/cauldron/bw_matchbox/blob/7c69b6f9d13ba38cea82b146121650f93507c28c/bw_matchbox/assets/templates/process_detail.html#L24).

**Comment by cmutel** [comment]
> What should be displayed for 'editors' role?

They see the "add match" button as it currently is now. But people without the role "editors" can't add matches, so there is no point showing them that option.

> What should be dsiplayed if current row has matched parameter?

For editors, nothing changes. For non-editors, see the section "Instead, they should see a "Match" column" in the initial issue description, giving three different possibilities.

I hope that is clear, please feel free to come back if we are still not understanding each other!

**Comment by lilliputten** [comment]
> > What should be displayed for 'editors' role?

> They see the "add match" button as it currently is now.

Before all links were sent to the page `/match`, which is absent. What address should I use instead for now?

> > What should be dsiplayed if current row has matched parameter?

> For editors, nothing changes. For non-editors, see the section "Instead, they should see a "Match" column" in the initial issue description, giving three different possibilities.

I can't see nothing about `matched` -- there only references to `match_type` (if I've got it right). (Before it used only to generate different icons and texts.) Should we use it somehow now?

**Comment by lilliputten** [comment]
Updated the PR: Added link to `/match/{process_id}` for editors. Parameter `matched` still not used.

**Comment by lilliputten** [comment]
Made some fixes for recent updates (in `ProcessesListDataRender.js`) -- there were some errors, see diagnostic screenshot:

![0817-161501](https://github.com/cauldron/bw_matchbox/assets/6855837/4b950ae1-eb98-4266-895d-15b4918b8cef)

> Fixed code for matched column content generation on process list template.
> 
> Restored `matched` parameter, code localized in `renderMatchCellContent` method, for editors role and unmatched condition generated primary button styled link (is it neccessary?), link text generating as before (`match_type` or 'Edit' for matched row, else 'Add').
>
> See commit [4912ec9](https://github.com/cauldron/bw_matchbox/commit/4912ec94b586a42d9593bbfbafe8334847fe693b).

PR #113.

![0817-162406](https://github.com/cauldron/bw_matchbox/assets/6855837/a82d5335-4049-4629-a521-f53f251d2942)
![0817-162442](https://github.com/cauldron/bw_matchbox/assets/6855837/f15cad83-4f55-4cb7-98e6-2ec43504b76e)
![0817-162617](https://github.com/cauldron/bw_matchbox/assets/6855837/2b093755-c1ff-4ab6-9551-e683fe076d54)
