### ISSUE TITLE
Match state does not update in table overview

### ISSUE THREAD

**Issue by marc-vdm** [cauldron/bw_matchbox#103]
The [second process](https://dare.cauldron.ch/process/33452) 'match type' status does not update after I updated the match.

![image](https://github.com/cauldron/bw_matchbox/assets/34626062/36b2447d-a8b4-465d-addb-98aae7daa039)

This is also -partially- the case in the process details, where we now see both a `proxy`, but also the type `No direct match available`

![image](https://github.com/cauldron/bw_matchbox/assets/34626062/62b75d3b-f5da-48b0-920e-e5922827690c)

When updating the match type, matchbox should overwrite the `match type` variable to reflect the new type.

**Comment by cmutel** [comment]
Probably a silly question, but is the old (stale) state persisted after a page reload?

**Comment by marc-vdm** [comment]
Unfortunately, yes ;)

**Comment by cmutel** [comment]
Should be fixed in 08f0da5f9a831f09bb49dd513d9116aed6dd51b9
