### ISSUE TITLE
Resolved comment threads should have a distinct background color

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#123]
Should indicate a good result, so either a greenish color, a subtly dashed background, or something similar.

**Comment by lilliputten** [comment]
Fixed in PR #127.

![0901-154037](https://github.com/cauldron/bw_matchbox/assets/6855837/7cdbaa58-3a94-45c7-975e-752193507a52)
![0901-154047](https://github.com/cauldron/bw_matchbox/assets/6855837/9388b431-b90b-482b-b95e-d224399b6d47)
