### ISSUE TITLE
Comment expansion arrow color should indicate if there are unresolved comment threads

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#124]
Currently (AFAICT) this is the same regardless of the state of the comments. It should be red or otherwise indicate unresolved comment threads if they are present. Can stay the same if otherwise.

**Comment by lilliputten** [comment]
Fixed in PR #127.

![0901-154037](https://github.com/cauldron/bw_matchbox/assets/6855837/42882025-cd09-4afe-be13-25986c5872ba)
![0901-154047](https://github.com/cauldron/bw_matchbox/assets/6855837/0b3d9ba7-0d31-4eec-aa6e-dce06b7eb163)
