### ISSUE TITLE
Allocation webpage

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#128]
# Allocation webpage

The purpose of this webpage is to take one inventory process dataset which produces more than one useful output, and to give the user the ability to split the inputs and biosphere flows among these multiple outputs. For example, in a combined heat and power plant, 30% of the fuel and 30% of the air emissions would be allocated to electricity, and the other 70% would be allocated to heat.

To do this we start with a page similar to the process detail one, the url is `allocate/<id>`:

<img width="546" alt="Screenshot 2023-09-01 at 11 06 12" src="https://github.com/cauldron/bw_matchbox/assets/645217/8f10a244-be09-4fb0-89d0-a78bf8800e70">

The layout above isn't the right one! It is just a copy of what we have in the process detail. For example, when putting exchanges into groups there is no need to show the production inputs, these **can't** move or be put into a group.

We then need the ability to move the **technosphere** and **biosphere** inputs into groups. **All** T/B inputs need to be put in a group.

<img width="609" alt="Screenshot 2023-09-01 at 11 07 31" src="https://github.com/cauldron/bw_matchbox/assets/645217/dd038474-b18b-4bd5-9b56-a8aa4d511315">

The number of groups doesn't depend on the number of products, this is up to the user to decide. So we need a button to create a new group. Groups should have labels chosen by the user, and the user can edit the labels afterwards (so an edit icon and some way to change the text is needed).

@lilliputten It is up to you on how these elements get put into the different groups, I had in mind drag and drop, but if you think it is better or easier to do something different than go with that. If we do do drag and drop then we should be able to hold <shift> or whatever modifier to select more than one element before dragging.

When all T/B inputs are in one (and only one) group, the UI transitions to the "allocation phase". Here we need to give allocation factors to each group per product:

<img width="552" alt="Screenshot 2023-09-01 at 11 08 42" src="https://github.com/cauldron/bw_matchbox/assets/645217/ba521fda-166e-43af-95ff-7a5787869730">

So group one could be allocated 0.2 to product 1, 0.2 to product 2, and 0.6 to product 3.

How the page transitions to the "allocation phase" is up to @lilliputten, but this shouldn't involve a server request. It needs to happen in the same page view.

The allocation factors are always numbers between 0 and 1. Zero and one are both allowed. There should be a validation check that these numbers fit within these (inclusive) bounds. The **sum** of allocation factors for each group should be one across all products.

In this view, I don't think we should show all the inputs in each group - there will be cases where there are 20 or more inputs in one group. Instead, we can give a brief summary on top, e.g. "7 tech / 4 bio", and then list the inputs as before, but make the height of the parent div fixed so that you can scroll within the group div. You can also implement this another way if that is more convenient for you, this is just a first idea.

Probably at the beginning of the "allocation phase" you should assume an equal allocation factor for each row, i.e. if there are three products the default allocation factor is 0.3333. To ensure that the numbers sum to one the last numerical field should not be editable - it should adjust dynamically to make sure the row values sum to one. The last value cannot be less than zero, this should raise an error.

At any point in the allocation, assuming there are valid allocation factors (i.e. sum is one), the user can save the state. This will be a `POST` request to `allocate/<id>`, this endpoint and its data format are not yet specified.

## Example data

I have created an example database for this development. [Here is the project file](https://ln5.sync.com/dl/7d16b6a10/4uqkds2t-5rdt2426-x5i3vc5j-bfuj2r7i), [here is the notebook I used to create it](https://ln5.sync.com/dl/366874170/s3uz2xrr-8s33mruh-747f2kg2-jyjacgzc).

**Comment by lilliputten** [comment]
Questions:

- Don't uderstand how much sections we need there:

> ...there is no need to show the production inputs...

So, we need only 2 sections: 'Technosphere Inputs' and 'Biosphere Inputs'? (But we will need 'Products' later, for 'Allocation mode'?)

- Is it correct that 'Allocation phase' should to start only when _all_ the available inputs have moved to the _only one_ group? Should it happens automatically, when we moved last available record? (Later I see smth about '...allocation factors for each group...' That is, the first assumption (about single group) was wrong?

- Does the 'Allocation mode' mean that we distribute the created (single) group between available products (with some factor coefficients)? (Don't uderstand why we have a few rows of groups on the sketch?) (We need to decide where and how the user should enter these factor numbers.)

To confirm:

- Groups are created by the user with arbitrary titles (taken with popup dialogs).
- Items moved to groups by drag-and-drop. (And added: to the end of group? to the sorted (in which order) positions? to the place wehre user has put them?)
- Users can move multiple items at once (by selecting them first; with Shift modifier?).
- We are displaying group contents in short way: only summary and few first/last records?
- We initialize the factor numbers equeally among the products.
- The last factor number should not be editable -- it's adjusted automatically, depending on other numbers, so the total value is equal to 1.
- The user can save the allocation results at any moment by clicking the 'Save' button (if there valid allocations have been made) -- and continue allocations. (The button can indicate whether the results have been already saved.)

-

**Comment by cmutel** [comment]
> Don't uderstand how much sections we need there:
>> ...there is no need to show the production inputs...

So, we don't need to show graphic 1 at all. We can start with graphic 2. By default there is one group. The products (production exchanges tell *how much* of each product is made by the process) can be shown, but are only listed, they aren't objects that users can move around.

> So, we need only 2 sections: 'Technosphere Inputs' and 'Biosphere Inputs'? (But we will need 'Products' later, for 'Allocation mode'?)

Yes

> Is it correct that 'Allocation phase' should to start only when all the available inputs have moved to the only one group ('...When all T/B inputs are in one (and only one) group...')? 

Yes. Each input box (either T or B) can only be in one group, sort of by definition. You can only drag it to one group, not more than one.

> Should it happens automatically, when we moved last available record? (Later I saw smth about '...allocation factors for each group...' That is, the first assumption (about single group) was wrong?)

I don't think automatically, people might want to review and think about the grouping. I would rather have a disabled button which only becomes activate once all inputs are put in a group.

> Does the 'Allocation mode' mean that we distribute the created (single) group between available products (with some factor coefficients)? (Don't uderstand why we have a few rows of groups on the sketch?) (We need to decide where and how the user should enter these factor numbers.)

See the improved graphic:

<img width="552" alt="264977868-ba521fda-166e-43af-95ff-7a5787869730" src="https://github.com/cauldron/bw_matchbox/assets/645217/57a296bb-ec14-4bf3-b1b4-3616e7213c56">

**Comment by cmutel** [comment]
> Groups are created by the user with arbitrary titles (taken with popup dialogs).

Yes, can also be edited inline instead of popup, as you prefer.

> Items moved to groups by drag-and-drop. (And added: to the end of group? to the sorted (in which order) positions? to the place wehre user has put them?)

We can add sorting later, let's get the basics down first.

> Users can move multiple items at once (by selecting them first; with Shift modifier?).

Yes

> We are displaying group contents in short way: only summary and few first/last records?

The user should be able to scroll within the group `div` to see all the contents.

> We initialize the factor numbers equeally among the products.
> The last factor number should not be editable -- it's adjusted automatically, depending on other numbers, so the total value is equal to 1.

Yes

> The user can save the allocation results at any moment by clicking the 'Save' button (if there valid allocations have been made) -- and continue allocations. (The button can indicate whether the results have been already saved.)

I think after saving there will be a redirect to a page which doesn't exist yet.

**Comment by lilliputten** [comment]
PR #135: Allow multiple input rows selction, moving multiple items at once, modified cursors ('add-pointer' for selectable table rows, 'grab' for selected rows, only selected rows allowed to drag), disabled any actions (select, drag) for 'production' table.

![0905-222119](https://github.com/cauldron/bw_matchbox/assets/6855837/52819e7e-e06e-4597-9e33-83b9c8cef645)
![0905-222216](https://github.com/cauldron/bw_matchbox/assets/6855837/8a41123b-47fa-4842-a3e6-38001b622416)

**Comment by cmutel** [comment]
The return format should be a JSON object something like:

```python
{
    'process': int,
    'groups': [{
        'name': str,
        'technosphere': ["integer ids (to be provided by initial API call)"],
        'biosphere': ["integer ids (to be provided by initial API call)"],
        }]
    }],
    'allocation': [{
        'product': int,
        'groups': [{
            'name': str,
            'factor': float,
        }]
    }] 
}
```

**Comment by lilliputten** [comment]
> The return format should be a JSON object something like:
> 
> ```python
> {
>     'process': int,
>     'groups': [{
>         'name': str,
>         'technosphere': ["integer ids (to be provided by initial API call)"],
>         'biosphere': ["integer ids (to be provided by initial API call)"],
>         }]
>     }],
>     'allocation': [{
>         'product': int,
>         'groups': [{
>             'name': str,
>             'factor': float,
>         }]
>     }] 
> }
> ```

Should we ensure to have unique group names here? Or only order is important?

**Comment by lilliputten** [comment]
Do we need to check other valid fraction number conditions except overall summ of 1?

**Comment by lilliputten** [comment]
The actual data sample to sent to server (now just displaying in a modal dialog):

```javascript
{
  groups: [
    {
      name: 'Group name',
      technosphere: [
        201,
        195,
        196,
        197,
        202,
        198,
        200,
        194
      ],
      biosphere: [
        80,
        79,
        77,
        74,
        75,
        78,
        76,
        73
      ]
    },
    {
      name: 'Second group',
      technosphere: [
        199
      ],
      biosphere: []
    }
  ],
  allocation: [
    {
      product: 191,
      groups: [
        {
          name: 'Group name',
          factor: 0
        },
        {
          name: 'Second group',
          factor: 0
        }
      ]
    },
    {
      product: 193,
      groups: [
        {
          name: 'Group name',
          factor: 0
        },
        {
          name: 'Second group',
          factor: 0
        }
      ]
    },
    {
      product: 190,
      groups: [
        {
          name: 'Group name',
          factor: 0
        },
        {
          name: 'Second group',
          factor: 0
        }
      ]
    },
    {
      product: 192,
      groups: [
        {
          name: 'Group name',
          factor: 1
        },
        {
          name: 'Second group',
          factor: 0
        }
      ]
    },
    {
      product: 189,
      groups: [
        {
          name: 'Group name',
          factor: 0
        },
        {
          name: 'Second group',
          factor: 1
        }
      ]
    }
  ]
}
```

**Comment by lilliputten** [comment]
Finished in PR #140.

**Comment by cmutel** [comment]
> Should we ensure to have unique group names here? Or only order is important?
> If it's not important, then it's not neccessary to duplicate the names (in allocation[].groups[].name)?

I think it will be much easier to match the group names than the order. In theory the order can be the same, this would be enough to link the group members to their allocation factors, but I prefer using the names as keys in a hash table.

> Do we need to check other valid fraction number conditions except overall summ of 1?

Yes, the values shouldn't be less than 0.

> Here are 3 groups, last is empty, second with only one production item.

You already added a check that empty groups are not allowed, that is perfect.

**Comment by lilliputten** [comment]
So, now we need only to add a server API method or redirect?
