### ISSUE TITLE
Allocation webpage: Help message text change

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#131]
This switch to the message "Drag inputs to groups to add them" is really nice, but after adding one input exchange, I think it should switch to "All inputs must be added to a group"

**Comment by lilliputten** [comment]
What exact text? 'To group' or 'to groups'?

**Comment by lilliputten** [comment]
Fixed in [dev-230901-issue-128-allocation-page ee70929] Issue #131: Change the help tooltop to 'All inputs must be added to a group' when at least one input has added.

**Comment by lilliputten** [comment]
Fixed in PR #135.
