### ISSUE TITLE
Allocate table: Using `control` key is not a great option

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#138]
The `control` key opens a context panel, i.e. back, forward, reload, etc. on Firefox (MacOS) and Safari (MacOS). Maybe another modifier key would be better?

**Comment by lilliputten** [comment]
We can use shift, but this combination is usually used to highlight a number of objects (from last to current).

Do we have other options?

Will it be ok to select using regular click? Probably not: we will need some selector to switch 'single' and 'multiple' modes?

**Comment by cmutel** [comment]
Simple click seems OK to me, if that would work. Thanks!

**Comment by lilliputten** [comment]
Fixed in PR #139.
