### ISSUE TITLE
Add filter for manual matches

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#142]
In addition to `filter by None | Matched | Unmatched | Waitlist`, we should also be able to filter by `Manual match`.

To achieve this pass `filter=manual-match`, see https://github.com/cauldron/bw_matchbox/commit/385a0e93938dce9688c45ea1d6bac8e348ab2e18.

**Comment by lilliputten** [comment]
If I got it correctly, I just need to add an extra parameter to allow users send 'manual-match' to the server. Is that all there is to do for this task? How can I check the result?

**Comment by lilliputten** [comment]
Implemented in PR #145.

![20231121-220722](https://github.com/cauldron/bw_matchbox/assets/6855837/41a7b202-e422-4b9a-a841-e3fe17932fc3)
