### ISSUE TITLE
Poor layour in comparison view

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#148]
<img width="1332" alt="Screenshot 2023-11-24 at 11 47 15" src="https://github.com/cauldron/bw_matchbox/assets/645217/8e13d34c-9140-4d73-be8a-dbaec41434a0">

The `amount` column is taking up way too much space, and the `name` is not usable.

**Comment by lilliputten** [comment]
Fixed in PR #149.

![20231124-180755](https://github.com/cauldron/bw_matchbox/assets/6855837/f78370ad-056d-4144-97d6-140d5db9c54f)
