### ISSUE TITLE
HTML input boxes use `placeholder` instead of actual value

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#15]
When searching (e.g. https://dare.cauldron.ch/match/30102), the search result page uses the `placeholder` attribute. It would be much nicer to have this be the actual input value so that it is easy to change slightly for another search. As a placeholder it disappears when you start typing, and can't be highlighted.

**Comment by lilliputten** [comment]
I think I've fixed it on index page in last PR #19. Check, pls, is this solution ok? Are there the same text fields on another pages (will take a look by myslef later)?
