### ISSUE TITLE
LCIA scores: change column ordering

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#152]
Should be:

* Name
* Unit
* Ratio
* Original
* Relinked

**Comment by lilliputten** [comment]
Do you mean to add order (sort) mode selector?

**Comment by lilliputten** [comment]
Do you mean to add control to allow to choose sort method?

Do we need ascending/descending modifier?

**Comment by lilliputten** [comment]
Should 'name' sort mode make sort by 'catagory' field?
