### ISSUE TITLE
Allocation workflow

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#156]
The allocation workflow is great, but we don't have a way to get there from the index page.

- [ ] Check if [`sharedParams.databases.unallocated`](https://github.com/cauldron/bw_matchbox/blob/main/bw_matchbox/assets/templates/index.html#L150) is not `null`. If it is, do nothing else.
- [ ] Otherwise add another option to the `Databases` radio button, with the value "Unallocated" (this string, not value in the JSON array).
- [ ] Upon selecting this option, populate the process table as before. However, instead of a "Match" column, add a column with the label "Allocate". 
- [ ] This column should have a button with the URL reference [`allocate_url`](https://github.com/cauldron/bw_matchbox/blob/main/bw_matchbox/webapp.py#L596) if the value `allocated` is `false`.
- [ ] If `allocated` is `true`, then show a checkmark and the word "allocated', but without a link.

**Comment by lilliputten** [comment]
Should it look this way:

![20231206-155806](https://github.com/cauldron/bw_matchbox/assets/6855837/38eea050-132b-4a95-8603-c94394b855a6)

It's not a switch to retrieve other data from server, right? But only option to display that extra column?

What database have we to use for 'Allocate'? 'Source'?

Apparently, I'm wrong, but wouldn't it be better to add an 'Allocate' checkbox to allow this mode to be applied for each of the databases?

This way:

![20231206-160639](https://github.com/cauldron/bw_matchbox/assets/6855837/b5aab100-5145-490b-b0ba-90c506ae238b)

**Comment by lilliputten** [comment]
Didn't get any answers for the questions. I did it according to my understanding and hypotheses.

I assume that:

- The `sharedParams.databases.unallocated` field contains an (optional) database id.

- The returned data records for this database contain fields `allocated` and `allocate_url` (I see the second one in webapp method `processes`, not the first).

Please let me know if I'm wrong.

This task has been fixed (in the described way) in PR #159.

Screenshot with demo data (emulated statuses for `allocated` field):

![20231206-230829](https://github.com/cauldron/bw_matchbox/assets/6855837/a84558f3-2235-43c7-b100-e0b8c83331d0)

**Comment by lilliputten** [comment]
Finished with PR #159.
