### ISSUE TITLE
Add button to expand all collapsed cells

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#22]
Sorry, I didn't think this was needed until I started actually working with the tool... but actually it is useful, see e.g. https://dare.cauldron.ch/compare/33131/15652.

**Comment by lilliputten** [comment]
Fixed in #28.

![0804-211351](https://github.com/cauldron/bw_matchbox/assets/6855837/8147d680-f20a-4486-b8b1-86b5b79ab136)
