### ISSUE TITLE
Taking action in compare view should disable `replaceWithTargetHandler` button

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#34]
The `replaceWithTargetHandler` is meant to replace a list of process inputs with a reference to the process itself. If these inputs are modified, with the addition of inputs from the left hand side (`Shift row`), the removal of inputs (`Remove row`), the editing of a number, or the expansion of one input to its constituent inputs (`Expand row`), there is no longer a 1-to-1 correspondence with the original process, and the up arrow and `replaceWithTargetHandler` should be disabled (disappear).

The up arrow itself should also have a tooltip "Collapse process inputs".

**Comment by cmutel** [comment]
> I think I'll need some clarifications about the detailed conditions when we should hide that functionality. Eg, some user story (what should user do to disable this button).

I added some basic code to do this here: a9dc413a82d5c18f6557680a1414f55439df399e

@lilliputten, I guess you would like to either edit this to make it more consistent with the rest of the JS, or to animate the arrow disappearing via a class rather than setting `display`. So I am leaving this open even though it is working well enough, but setting the milestone to 1.1.

**Comment by lilliputten** [comment]
Fixed in PR #95.
