### ISSUE TITLE
Process detail list view looks dumb

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#39]
<img width="1618" alt="Screenshot 2023-08-05 at 09 18 01" src="https://github.com/cauldron/bw_matchbox/assets/645217/96908992-b3dd-4fd1-850c-a26fcbec6336">

The list should either be split across multiple columns, or turned into some other display form so we don't have to scroll so far to see the inputs tables.

**Comment by lilliputten** [comment]
Fixed in PR #74.

![0808-151824](https://github.com/cauldron/bw_matchbox/assets/6855837/55b53e65-7f10-405f-a3d8-659c6ac4affe)
