### ISSUE TITLE
Default filter in index page should be `None`

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#45]
#41 Added filters, but was poorly specified. The default filter should be `None`, i.e. omit the `filter` argument in the GET request completely.

**Comment by lilliputten** [comment]
So, we need to:

(1) Add 4th 'none' switch?

(2) Add 'zero' (default and hidden) state, when no filter options has selected? Do we need to have possibility to reset to 'none' state if some of real options had already selected?

**Comment by cmutel** [comment]
> (1) Add 4th 'none' switch?

Yes, but this should be the first in the set and the default selection.

> (2) Add 'zero' (default and hidden) state, when no filter options has selected? Do we need to have possibility to reset to 'none' state after some of real options had already selected?

If it is easier, we can just accept a blank `filter` argument in the API and ignore it. But *one* of the filters (including no filter) always needs to be selected, and yes, one could go back to no filter after trying one of the other ones.

**Comment by cmutel** [comment]
Allow for blank `filter` argument in d8b9d754c06ab3218872a6bdc47c9a22e900c920.

**Comment by lilliputten** [comment]
Fixed in #47.
