### ISSUE TITLE
Rewrite index page for table population via API call

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#5]
* Add toggle for random / sort by name / sort by location / sort by unit
* Add simple pagination using `offset` and `limit` API parameters

Needs #4 to be fixed first.

**Comment by cmutel** [comment]
@lilliputten API endpoint added, see docs here: https://github.com/cauldron/bw_matchbox/blob/main/bw_matchbox/webapp.py#L233

**Comment by lilliputten** [comment]
Is it possible to return the total number of available records for these conditions along with a list of results? In this case, we can show a more complete navigation.

I'm not sure (had some issues once) but it's probably not good to return the list in the root of the json. Maybe, just in case, it is better to return the data in the form `{ list: [...] }` (or even: `{ list: [...], total_records: {N} }`)?

**Comment by cmutel** [comment]
Fixed in 4d320cd. Now returns `{"total_records": N, "data": [objs]}`.

**Comment by lilliputten** [comment]
Implemented:

- Order by switch (radio group).
- Dynamic data loading.
- Reloading for 'random' order mode.
- 'Load more' feature for all the other order modes.

Some tests and aproovments required. Expected feedback.

PR #19.
