### ISSUE TITLE
Add modal dialogue when `waitlist`-ing a process

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#53]
The ability to set the `waitlist` attribute was added in c1b45f7cfa7e719d813ef4bb6d18762131bba132.

However, it would be much nicer to have a modal dialogue that would allow users to add a comment on *why* a process is being waitlisted. It could be quite simple, just a textbox with the title "Waitlist this process", label "Comment", and cancel / confirm buttons.

On clicking confirm, there should be two API calls. One to:

`/add-attribute/<process id>?attr=waitlist&value=1`

And the other to:

`/add-attribute/<process id>?attr=waitlist_comment&value=<comment text>`

**Comment by cmutel** [comment]
> Did I get this correct, supposing that this modal should be opened by clicking Waitlist button on the process_detail page (somewhere in the markWaitlist function?

Yes, exactly. I just thought a model window would be easiest, but however you want to do it, we need a way to be able to insert an (optional) comment when clicking the waitlist button, as it is easy to forget the reason why we waitlisted something afterwards.

**Comment by lilliputten** [comment]
Some aditional fixes in PR #73.
