### ISSUE TITLE
Easier matching: highlight same Activity/Product/Location/Unit

### ISSUE THREAD

**Issue by marc-vdm** [cauldron/bw_matchbox#56]
![image](https://github.com/cauldron/bw_matchbox/assets/34626062/7f76f76f-83bc-4fe8-a951-96122451f034)

If in this search (when matching activities), we could highlight already the same Activity/Product/Location/Unit as the original process, this could speed up finding appropriate matches. 

In this case, row 1-4 could highlight the Unit, row 4 also the location.

If possible, maybe it could make sense to also sort the list based on the matching items? (so row 4 would be on top as it has 2 matching columns) Though this may be a bit more difficult to implement.

edit: for reference, this is `/process/33475`

**Comment by lilliputten** [comment]
I don't understand the task (looking at the 1st part, for beginning).

(1) I can't get this page (`/process/33475`) on local data.

(2)  I can't get nothing similar to this screenshot on the server page (https://dare.cauldron.ch/process/33475)

I see this page:

![0808-204801](https://github.com/cauldron/bw_matchbox/assets/6855837/a97c0d76-a1be-4544-971b-2bd0a71c026d)

And I can't figure out how can I start the search (for 'transport, highspeed train,') there -- don't see no 'search' buttons or input fields.

Is it really search results there? How can I reproduce it?

(3) I suppose that 'original process' here is the data in the process detail section, above the search?

I think, first that I need -- it's the way to reproduce this case.

**Comment by lilliputten** [comment]
Most likely, I need to use `match/33475` instead of `process/33475`? At least, I can get smth more similar to screenshot on link https://dare.cauldron.ch/match/33475.

This is it?

I'll try to find smth on local dataset.

**Comment by lilliputten** [comment]
Made this just for example (not sure what highlighting effect will be used). This way?

![230808-match-highlights-01](https://github.com/cauldron/bw_matchbox/assets/6855837/e53c2f70-da59-4593-94a7-33e329b40968)

**Comment by cmutel** [comment]
Yes, this is exactly it. It can be very helpful if there are many different search results returned.

**Comment by lilliputten** [comment]
Preliminary fixed in PR #81.

Previews:

![0809-025941](https://github.com/cauldron/bw_matchbox/assets/6855837/53dad7f3-9ec5-4315-ade6-e76caec934ac)
![0809-030158](https://github.com/cauldron/bw_matchbox/assets/6855837/704db01f-93bb-4b17-8db7-429ffafe6a86)
