### ISSUE TITLE
Show matched inputs in left-hand side `compare` table

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#59]
<img width="984" alt="Screenshot 2023-08-07 at 15 54 01" src="https://github.com/cauldron/bw_matchbox/assets/645217/fd123d3b-dbfd-46e1-b74c-207d3271b171">

 The `processes` endpoint already returns the `matched` boolean.

It should be pretty easy to add `<i class="fa-solid fa-check"></i>` in front of the name on the *left hand* table if the `matched` attribute is true.

**Comment by cmutel** [comment]
@lilliputten I don't know how to do this with the structure we have, it seems that there is one template for both tables in `CompareCore.js`.

**Comment by lilliputten** [comment]
I can't see that `matched` attribute for `compare` page data. Should I try to add it on the server-side?

For now I see only these data (example):
```
amount: 0.00005343307507347048
amount_display: "5.3e-05"
input_id: 650
location: "United States"
name: "Stationery; at manufacturer"
row_id: "9"
unit: ""
url: "/process/650"
```

**Comment by lilliputten** [comment]
Fixed using this code on the server (`"matched": bool(exc.input.get('matched'))`).

Demo screenshot (with fake `matched` attributes -- can't see no real data for them):

![0809-153741](https://github.com/cauldron/bw_matchbox/assets/6855837/d96a04b8-8c8c-417d-844c-cdbd60c216ba)

PR #84.
