### ISSUE TITLE
Minor: Waitlist dialog shouldn't require a comment

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#61]
Comments are useful but not required. The code disabling it before typing can be removed.

**Comment by cmutel** [comment]
@lilliputten I hacked my way to make the save button always available [here](https://github.com/cauldron/bw_matchbox/commit/9dd26ac059ac385dd16ae880fed885e628e36bd0); please feel free to clean this up!

**Comment by lilliputten** [comment]
> @lilliputten I hacked my way to make the save button always available [here](https://github.com/cauldron/bw_matchbox/commit/9dd26ac059ac385dd16ae880fed885e628e36bd0); please feel free to clean this up!

It looks ok (if it's not needed). Will remove commented code tomorrow.

**Comment by lilliputten** [comment]
Is it fixed? (Plus some additional fixes in PR #73.)
