### ISSUE TITLE
Calling `add-attribute` in series can cause race conditions

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#67]
See 171b30d5ee020a079236981098b8f1b5d2ba1679 for one case where this was causing issues. I think there are other places in the same file where calls could lead to data loss.

(This should be fixed in the underlying Brightway library but that isn't happening anytime soon...)

**Comment by cmutel** [comment]
To clarify a bit, a call to `add-attribute` should wait for a response before another call is made to this endpoint.

**Comment by lilliputten** [comment]
What do you want to do here?

I can make it like in `ProcessDetail.js:doMarkWaitlist` -- to call all the requests simultaneously and treat it as an `atomic transaction` -- the operation cosidered succesfull only if all the requests were successful.

**Comment by cmutel** [comment]
>  to make requests sequentially

Yes, exactly, you need to wait for the request to return successfully before the next one.

**Comment by lilliputten** [comment]
Fixed in PR #77 -- needs to be checked.
