### ISSUE TITLE
Improve compare cell highlighting and collapsing

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#68]
As a frequent user, I want the cell highlighting and collapsing to be more clever, so that I can more efficiently identify similarities and differences between two processes. Specifically, it would be nice if the following were supported:

- [ ] Holding down `<shift>` allows for highlighting more than one cell in a table, so that we can collapse two cells on the right hand side that correspond to one cell on the left hand side.
- [ ] Selecting a cell should highlight cells in the other table which have the same `unit` and `name`
- [ ] Selecting a cell should highlight cells in the other table whose absolute value of the `amount` field is within 2% of the source's absolute value of the `amount` field. We need absolute value because sometimes the sign is flipped but it is actually a corresponding exchange.
- [ ] Double-clicking on a cell in one table should also highlight all other cells *in the same table* which have the same `name` and `unit`.

**Comment by lilliputten** [comment]
That's serious. 👍

Does this 'highlighting' mean the same as 'ready to collapse'? Or another type of marking, just visual?

Should these highlightnings to be made in different colors?

Should highlightnings 2 (by unit and name) and 3 (by similar amount) to be made simultaneously? Or we need to have different modes (by switch somewhere on the page) of highlights?

For (1): how should multiple selection be started and stopped? To start, the user has to click row with the shift key (at any time, despite whether there is already a selection, or not)? Should the 'multiple' mode revert to 'single' if all entries except one are deselected? To stop he just has to click next (uselected) row without shift pressed? Or it should just cancel 'multiple' mode? But, in this case, how should we finish multiple selections (to make selected rows 'collapsed')?

**Comment by cmutel** [comment]
> Does this 'highlighting' mean the same as 'ready to collapse'? Or another type of marking, just visual? Should these highlightnings to be made in different colors?

Visual marking to help users identify, should be a different color/pattern.

> Should highlightnings 2 (by unit and name) and 3 (by similar amount) to be made simultaneously? Or we need to have different modes (by switch somewhere on the page) of highlights?

They can be simultaneous, the idea is to quickly see similarities in large lists of inputs (up to 50 on each side).

> how should multiple selection be started and stopped?

I think a similar pattern to other multiple selections should be possible. Basically, once you start holding down `<shift>` you are in multiple-selection mode. When you let it go, and rows are selected, they are collapsed into the same group. Otherwise you are in the mode we have now, which also works great. 

The double-clicking doesn't need to work in multiple selection mode, this is normally one process on the left hand side and `N` processes with the same name on the right hand side.

Not sure `<shift>` is the best, but it seemed like other modification keys could be problematic as they are already used for a lot.

**Comment by cmutel** [comment]
This would be nice to have, but is not necessary for now. Marking as won't fix for the time being.
