### ISSUE TITLE
Widen default Skeleton page width

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#7]
Skeleton uses 960 px for content width, but this can cause problems with larger tables leading to a lot of vertical scrolling. A wider reasonable width could be used, maybe 1280 or even 1600.

@lilliputten Please look into this.

**Comment by lilliputten** [comment]
PR #13.

**Comment by cmutel** [comment]
@lilliputten Easy mode is to put "Fixes #13" in the PR message which will auto-close this issue on merging.
