### ISSUE TITLE
New waitlisting functionality does not add process to waitlist

### ISSUE THREAD

**Issue by marc-vdm** [cauldron/bw_matchbox#75]
The new waitlisting functionality (where we can add comments) does not add the process to the waitlist. After entering a comment and closing the dialog the process shows `WAITLISTED` as status, but cnce I refresh the process page the status is gone. The process does not show up to the `Waitlist`

**Comment by cmutel** [comment]
@lilliputten This is the race condition in #67. The code to be modified is here: https://github.com/cauldron/bw_matchbox/blob/059bf108e6c10693dc34ba23950f65194e7a424c/bw_matchbox/assets/js/ProcessDetail/ProcessDetail.js#L105

**Comment by cmutel** [comment]
The underlying problem is that the code loads the entire database row with all columns, and writes all column values instead of just doing an atomic update on the fields that changed. But this is quite some work to change so we just need to fix the API call sequence.

**Comment by cmutel** [comment]
> Does it mean, that the server code isn't suitable for true multiuser/highload modes?

Yes. But the intent is never for more than a few people to use this at one time, so it is fine.
