### ISSUE TITLE
In `process_detail` view, `No Match Needed` button is always disabled

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#78]
Probably a regression introduced in #77?

**Comment by lilliputten** [comment]
I made 'disabled' all buttons without user actions (and for which I couldn't find any potentional changes what could turn them into interactive). Probably, we need re-check it.

**Comment by cmutel** [comment]
I think we can just remove `disabled`?

**Comment by cmutel** [comment]
Pushed a temp fix in 0eae36d0dc11d00abac04693eac536a0252b6fa6, we need this working.

**Comment by lilliputten** [comment]
Oh, I see there was 'onClick' handler. I missed it.

**Comment by cmutel** [comment]
@lilliputten is my fix OK? If so, please close. Thanks!

**Comment by lilliputten** [comment]
> @lilliputten is my fix OK? If so, please close. Thanks!

Yes, of course -- active button (with onclick event handler) shouldn't be disabled.

**Comment by lilliputten** [comment]
Done.
