### ISSUE TITLE
Make good modal widget and fix existing modals

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#8]
It would be good to remake modal window. Now it's little weird -- large thing, sometimes few-screens height. It should be displayed over the page, contain nested scrolling, shouldn't affect scroll and state of the original page, if possible should be closed by esc keypress.

**Comment by lilliputten** [comment]
PR #21.

Modal screenshot:

![0804-003836](https://github.com/cauldron/bw_matchbox/assets/6855837/b2a7e923-7eae-4d12-82ea-b5b7b92c6a5a)
