### ISSUE TITLE
Adapt collapsing JS code to pre-collapsed elements

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#9]
2d8257d added checks for similarity, so some cells will be pre-collapsed. The JS and CSS code should be adapted to show these cells correctly.

**Comment by cmutel** [comment]
From @lilliputten: "Hi. I don't understand this: What is this thing about? Is this bug for my recent changes? Is it for me?"

Yes, that's why you are assigned :) From the provided link you can see that [we are adding `collapsed` attributes to some elements in the `source_data` and `target_data` arrays](https://github.com/cauldron/bw_matchbox/blob/2d8257d9415511201a9d52a295b8c55040603144/bw_matchbox/webapp.py#L502). These objects should be already be collapsed when the page renders.

**Comment by lilliputten** [comment]
Ok, yes. Now I see it. I have this algorithm to render collapsed rows (aimed to render previously collapsed rows when switching pages -- for the pagination feature). I'll add processing of those fields (`collapsed`) and will make some tests (it's untested for now). I'll do it later as a separate task.

**Comment by lilliputten** [comment]
I'm looking at this code:

```python
            node['collapsed'] = candidate['collapsed'] = True
            node['collapsed-group'] = candidate['collapsed-group'] = \
                "Collapsed-{}-{}".format(index, "".join(random.choices(string.ascii_letters, k=6)))
```

As far as I understand, this code doesn't save information about the corresponding collapsed records.

But for the correct operation of this algorithm on the client side (to be able to un-collapse rows by pairs) we need to have this information. (We need to know the second row to un-collapse when click on the first collapsed row.)
