### ISSUE TITLE
Add ability for reviewers to comment on `process_detail` page

### ISSUE THREAD

**Issue by cmutel** [cauldron/bw_matchbox#92]
On `process_detail` pages **where `is_proxy` is true**, we need the ability to add, see, and resolve comments.

We need some type of window or panel that can be displayed, either sliding from a side with a "hamburger"/similar icon, or modal summoned from clicking a button, or whatever. This new panel should:

- Have the ability to create a new comment thread (name and content)
- Have the ability to see existing threads and their status

For now I don't think we need to be able to search. I was thinking that we would list all comment threads (if any) by the thread name, have them start collapsed with a clear way to expand them, and include some kind of marker showing if the thread is resolved or unresolved. Unresolved threads should be shown at the top before any resolved threads are shown.

**Comment by cmutel** [comment]
> What differences should be there between these pages?

The `comments` page is primarily for reviewing comments - the comment model or panel in the `process_detail` page is about adding or responding to comments. Moreover, the comments are limited to the specific process being discussed.

> Probably we don't need that large block of filters and need to display only the threads associated with the current processes?

Yes, exactly, only the current process being displayed. I don't think we need any filters, but we do need:

- Comment threads start out collapsed but can be expanded
- Clear visual indication (text plus color, for example) of whether a thread is resolved or not
- Resolved threads are sorted to be lower down than unresolved threads. The second level of sorting should be by datetime of last modification, with most recent shown first.

**Comment by lilliputten** [comment]
Fixed (preliminary) in PR #118.

Previews for reference:

![0822-015559](https://github.com/cauldron/bw_matchbox/assets/6855837/ce795255-9db3-4a71-b1f3-d8afb5d6b8e6)
![0822-015707](https://github.com/cauldron/bw_matchbox/assets/6855837/ca6189f5-34b5-4767-9f5b-1d40f5ad3627)

Some todo's:

- To add some visual styles to distinguish open/resolved threads.
- Use some statistics info to fill 'empty' space reserved to loader splash (or to redesign the way to show 'busy' status?).
- Smth else (have I forgot smth)?

**Comment by cmutel** [comment]
@lilliputten Thanks, this is really nice! It works well.

The visual improvements are nice but not the top priority for now. Please turn them into issues but don't start work on them for now.

**Comment by lilliputten** [comment]
> @lilliputten Thanks, this is really nice! It works well.
> 
> The visual improvements are nice but not the top priority for now. Please turn them into issues but don't start work on them for now.

Ok. But not all of those tasks are 'visual'. Es6 modules (at least) is internal task. But I've got you. I'm expecting your updates about next priorities.
